version: "3.9"

services:

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - vol_wp:/vol_wp
    links:
      - nw_web

  wordpress:
    build: requirements/wordpress/
    volumes:
      - vol_wp:/vol_wp
    depends_on:
      - nginx
      - mariadb
    links:
      - nw_web
      - nw_db

  mariadb:
    build: requirements/mariadb/
    volumes:
      - vol_db:/vol_db
    links:
      - nw_db

volumes:
  vol_wp:
  vol_db:

networks:
  nw_web:
  nw_db:
