version: "3.9"

services:

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - vol_wp:/vol_wp
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/
    # ports:
    #   - "9000:9000"
    volumes:
      - vol_wp:/vol_wp
    env_file:
      - .env
    depends_on:
      - nginx
      - mariadb
    restart: unless-stopped

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        - MYSQL_ROOT_PASSWD=maria42
        - MYSQL_USER_NAME=user42
        - MYSQL_USER_PASSWD=user42
        - MYSQL_DB_NAME=db42
    # ports:
    #   - "3306:3306"
    volumes:
      - vol_db:/vol_db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  vol_wp:
  vol_db:
