version: "3.9"

services:

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - vol_wp:/vol_wp
    env_file:
      - .env
    networks:
      - nw_inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/
    # ports:
    #   - "9000:9000"
    volumes:
      - vol_wp:/vol_wp
    env_file:
      - .env
    networks:
      - nw_inception
    depends_on:
      - nginx
      - mariadb
    restart: unless-stopped

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        - MYSQL_ROOT_PASSWD=maria42
        - MYSQL_USER_NAME=wpuser42
        - MYSQL_USER_PASSWD=wppass42
        - MYSQL_DB_NAME=wordpress42
    # ports:
    #   - "3306:3306"
    volumes:
      - vol_db:/vol_db
    env_file:
      - .env
    networks:
      - nw_inception
    restart: unless-stopped

volumes:
  vol_wp:
  vol_db:

networks:
  nw_inception:
    name: nw_inception
