version: "3.9"

services:

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - vol_wp:/vol_wp
    restart: unless-stopped
    tty: true

  wordpress:
    build: requirements/wordpress/
    # ports:
    #   - "9000:9000"
    volumes:
      - vol_wp:/vol_wp
    depends_on:
      - nginx
      - mariadb
    restart: unless-stopped
    tty: true

  mariadb:
    build: requirements/mariadb/
    # ports:
    #   - "3306:3306"
    volumes:
      - vol_db:/vol_db
    restart: unless-stopped

volumes:
  vol_wp:
  vol_db:
