version: "3.9"

services:

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - vol_wp:/home/yonishi/data
    env_file:
      - .env
    networks:
      - nw_main
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress/
      args:
        - WP_HOMEPATH=${WP_HOMEPATH}
    volumes:
      - vol_wp:/home/yonishi/data
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWD
      - MYSQL_USER_NAME
      - MYSQL_USER_PASSWD
      - MYSQL_DB_NAME
      - WP_HOMEPATH
      - WP_SITE_TITLE
    networks:
      - nw_main
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        - MYSQL_ROOT_PASSWD=${MYSQL_ROOT_PASSWD}
        - MYSQL_USER_NAME=${MYSQL_USER_NAME}
        - MYSQL_USER_PASSWD=${MYSQL_USER_PASSWD}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
    volumes:
      - vol_db:/vol_db
    env_file:
      - .env
    networks:
      - nw_main
    restart: unless-stopped

volumes:
  vol_wp:
  vol_db:

networks:
  nw_main:
